services:

  ephios:
    image: ghcr.io/ephios-dev/ephios:v0.21.0
    restart: unless-stopped
    hostname: django.ephios.myhpi.local
    environment:
      DEBUG: "False"
      TRUST_X_FORWARDED_PROTO: "True"
      DATA_DIR: "/var/ephios/data/"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      CACHE_URL: "redis://redis/0"
      ALLOWED_HOSTS: "*"
      SITE_URL: "https://shifts.myhpi.de"
      # EMAIL_URL set in env file
      # DEFAULT_FROM_EMAIL set in env file
      # SERVER_EMAIL set in env file
      # ADMINS set in env file
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - django_data:/var/ephios/data/
    networks:
      - internal

  redis:
    image: redis:8.0-alpine
    restart: unless-stopped
    command: redis-server
    networks:
      - internal

  db:
    image: postgres:17.5
    hostname: db.ephios.myhpi.local
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
      - db-gateway-access

  nginx:
    image: nginx:1.28
    hostname: ephios.myhpi.local
    restart: unless-stopped
    networks: 
      - default
      - internal
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - django_data:/var/ephios/data/
    depends_on:
      - ephios

volumes:
  django_data: { }
  postgres_data: { }

networks:
  internal:
  default:
    name: default-network
    external: true
  db-gateway-access:
    name: db-gateway-access
    external: true
