global:
  scrape_interval: 5s
  scrape_timeout: 10s

scrape_config_files:
  - /etc/prometheus/scrape-configs/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
