ARG APPS="AlekSIS-Core@git+https://edugit.org/AlekSIS/official/AlekSIS-Core@a670c0eab6251a4c825ff67f144cf462d4ccfdde git+https://edugit.org/AlekSIS/onboarding/AlekSIS-App-Plank@1b98e8b60e73c2709af8fdaf6f77adfaea29c078"
ARG BUILD_DEPS="default-libmysqlclient-dev gcc pkg-config python3-dev"
ARG SYSTEM_DEPS="default-mysql-client-core"

FROM registry.edugit.org/aleksis/official/aleksis-core:a670c0ea