services:
  db:
    image: registry.edugit.org/aleksis/libs/postgres-aleksis:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=aleksis
      # POSTGRES_PASSWORD set in env
      - POSTGRES_DB=aleksis
    env_file:
      - .env
    networks:
      - internal

  valkey:
    image: valkey/valkey:8-bookworm
    networks:
      - internal

  app:
    build: .
    hostname: inventory.myhpi.local
    volumes:
      - aleksis_media:/var/lib/aleksis/media/
      - aleksis_backups:/var/lib/aleksis/backups/
    environment:
      - ALEKSIS_http__allowed_hosts=['inventory.myhpi.de']
      - ALEKSIS_valkey__host=valkey
      - ALEKSIS_database__disable_pool=True
      - ALEKSIS_database__host=db
      # ALEKSIS_database__password set in env
      - ALEKSIS_maintenance__debug=${ALEKSIS_maintenance__debug:-false}
      - PREPARE=1
      - RUN_MODE=uwsgi
      - ALEKSIS_auth__providers__openid_connect__verified_email=true
      - ALEKSIS_auth__providers__openid_connect__email_authentication=true
      # ALEKSIS_auth__providers__openid_connect__APPS__0__client_id set in env
      # ALEKSIS_auth__providers__openid_connect__APPS__0__secret set in env
      - ALEKSIS_auth__providers__openid_connect__APPS__0__name=Example
      # ALEKSIS_auth__providers__openid_connect__APPS__0__provider_id set in env
      # ALEKSIS_auth__providers__openid_connect__APPS__0__settings__server_url set in env
      - ALEKSIS_auth__providers__openid_connect__APPS__0__verified_email=true
      - ALEKSIS_auth__providers__openid_connect__APPS__0__email_authentication=true
    env_file:
      - .env
    ports:
      - 8794:8000
    depends_on:
      - db
      - valkey
    networks:
      - internal
      - default

  worker:
    build: .
    volumes:
      - aleksis_media:/var/lib/aleksis/media/
      - aleksis_backups:/var/lib/aleksis/backups/
    tmpfs:
      - /var/www/.cache/
    environment:
      - ALEKSIS_http__allowed_hosts=['inventory.myhpi.de']
      - ALEKSIS_valkey__host=valkey
      - ALEKSIS_database__disable_pool=True
      - ALEKSIS_database__host=db
      # ALEKSIS_database__password set in env
      - ALEKSIS_maintenance__debug=${ALEKSIS_maintenance__debug:-false}
      - ALEKSIS_selenium__url="http://firefox:4444"
      - PREPARE=0
      - RUN_MODE=celery-worker
      - ALEKSIS_auth__providers__openid_connect__verified_email=true
      - ALEKSIS_auth__providers__openid_connect__email_authentication=true
      # ALEKSIS_auth__providers__openid_connect__APPS__0__client_id set in env
      # ALEKSIS_auth__providers__openid_connect__APPS__0__secret set in env
      - ALEKSIS_auth__providers__openid_connect__APPS__0__name=Example
      # ALEKSIS_auth__providers__openid_connect__APPS__0__provider_id set in env
      # ALEKSIS_auth__providers__openid_connect__APPS__0__settings__server_url set in env
      - ALEKSIS_auth__providers__openid_connect__APPS__0__verified_email=true
      - ALEKSIS_auth__providers__openid_connect__APPS__0__email_authentication=true
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - internal

  scheduler:
    build: .
    environment:
      - ALEKSIS_http__allowed_hosts=['inventory.myhpi.de']
      - ALEKSIS_valkey__host=valkey
      - ALEKSIS_database__disable_pool=True
      - ALEKSIS_database__host=db
      # ALEKSIS_database__password set in env
      - ALEKSIS_maintenance__debug=${ALEKSIS_maintenance__debug:-false}
      - PREPARE=0
      - RUN_MODE=celery-beat
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - internal

  firefox:
    image: docker.io/selenium/standalone-firefox:4.32
    shm_size: 2gb
    environment:
      - ALEKSIS_http__allowed_hosts=['inventory.myhpi.de']
    networks:
      - internal

volumes:
  postgres_data:
  aleksis_media:
  aleksis_backups:

networks:
  internal:
  default:
    name: default-network
    external: true
