ARG APPS="AlekSIS-Core==5.0.0b4.dev0+20260415182832.e334348b AlekSIS-App-Plank==1.0.0b1.dev0+20260407150814.fd8c4ae6"
ARG BUILD_DEPS="default-libmysqlclient-dev gcc pkg-config python3-dev"
ARG SYSTEM_DEPS="default-mysql-client-core"

FROM registry.edugit.org/aleksis/official/aleksis-core:e334348b