ARG APPS="AlekSIS-Core==5.0.0b4.dev0+20260215164807.3e9f06e0 AlekSIS-App-Plank==1.0.0b0"
ARG BUILD_DEPS="default-libmysqlclient-dev gcc pkg-config python3-dev"
ARG SYSTEM_DEPS="default-mysql-client-core"

FROM registry.edugit.org/aleksis/official/aleksis-core:3e9f06e0